### ISSUE TITLE
A function is not defined

### ISSUE THREAD

**Issue by xiaohunshui** [LouisRouss/Diffusion-Based-Model-for-Colorization#3]
There is no definition of partial in trainer.py line 77, can you tell me how to implement it?

**Comment by xiaohunshui** [comment]
![image](https://user-images.githubusercontent.com/32764162/157077082-fed819f7-2ed0-434a-b38b-500ee60ceaab.png)

**Comment by LouisRouss** [comment]
Indeed an import was missing:

from functools import partial

**Comment by xiaohunshui** [comment]
Thank you for your reply, I have solved it with your help!
